/**
 * Module interface for the Emscripten-generated wasm exposing the
 * functions used across the TS codebase (aiWorker.ts, wasm helpers, html).
 *
 * Extend as needed when you call additional exported functions from C.
 * NOTE: this interface and these comments were generated by an LLM,
 * NOTE: they are specific to domino-ai repo and are a chore to do by hand...
 * NOTE: and they may be made
 */
export interface DominoAiModule extends EmscriptenModule {
  // Memory: Note that with WASM_WORKERS, this buffer is a SharedArrayBuffer
  wasmMemory: WebAssembly.Memory & { buffer: SharedArrayBuffer };

  // Initialization / Fallback
  _init_fact(): void;
  _get_fallback_ptr(): number; // returns pointer/offset to fallback atomic
  _get_fallback(): number; // returns fallback flag (int)
  _reset_fallback(): void;

  // Basic Constants / Enums (return small ints)
  _get_LEFT(): number;
  _get_RIGHT(): number;
  _get_PERFECT_PICK(): number;
  _get_IMPERFECT_PICK(): number;
  _get_PASS(): number;

  // Game / Object Allocators and Pointer Management
  _alloc_game(): number; // returns pointer (as integer) to allocated Game
  _alloc_move(): number; // returns pointer to allocated Move
  _alloc_max_move_arr(): number; // returns pointer to an array of Move
  _alloc_int(): number; // returns pointer to an int
  _deref_int(ptr: number): number; // dereference int pointer
  _alloc_float(): number; // returns pointer to a float
  _deref_float(ptr: number): number; // dereference float pointer

  // High-level Helpers (used in HTML template)
  _get_number_of_players(): number;
  _get_pips(): number;
  _get_current_player(): number;

  // Game State Manipulators (from wasm.c / game.c wrappers)
  _init_game(gamePtr: number): void;
  _print_game(gamePtr: number): void;
  _get_hands(gamePtr: number): number; // returns Hands*
  _set_hand_size(gamePtr: number, player: number, size: number): void;
  _set_turn(gamePtr: number, player: number): void;
  _get_turn(gamePtr: number): number;
  _get_snake(gamePtr: number): number; // returns Snake*
  _collapse_piece(
    player: number,
    handsPtr: number,
    left: number,
    right: number,
  ): void;
  _absent_piece(
    player: number,
    handsPtr: number,
    left: number,
    right: number,
  ): void;
  _emit_collapse(handsPtr: number): void;

  // Move Information Getters
  _get_playing_moves(
    gamePtr: number,
    playingMovesArrPtr: number,
    numberOfPlayingMovesPtr: number,
    cantPassPtr: number,
  ): void;
  _get_perfect_picking_moves(
    gamePtr: number,
    pickingMovesArrPtr: number,
    numberOfPickingMovesPtr: number,
  ): void;
  _get_playable_perfect_picking_moves(
    gamePtr: number,
    playablePickingMovesArrPtr: number,
    numberOfPlayablePickingMovesPtr: number,
  ): void;

  // Move Population Helpers (populate C move structs from components)
  _populate_move_from_components(
    movePtr: number,
    type: number,
    left: number,
    right: number,
  ): void;
  _populate_imperfect_picking_move(movePtr: number, amount: number): void;

  // AI-related Wrapper used by aiWorker.ts
  _populate_move_by_ai(
    gamePtr: number,
    movePtr: number,
    playingMovesArrPtr: number,
    numberOfPlayingMoves: number,
    depth: number,
    scorePtr: number,
    numberOfExploredNodesPtr: number,
  ): void;

  // Play / Pick / Pass Operations that act on game by pointer
  _play_move_by_pointer(gamePtr: number, movePtr: number): void;
  _pass(gamePtr: number): void;
  _perfect_pick_by_pointer(gamePtr: number, movePtr: number): void;
  _imperfect_pick_by_pointer(gamePtr: number, movePtr: number): void;

  // Helper Getters for Move Contents
  _get_left_of_move(movePtr: number): number;
  _get_right_of_move(movePtr: number): number;
  _get_type_of_move(movePtr: number): number;

  // Stuff the LLM forgot somehow...
  _print_playing_moves(
    playingMovesArrPtr: number,
    numberOfPlayingMovesPtr: number,
  ): void;
  _print_picking_moves(
    playingMovesArrPtr: number,
    numberOfPlayingMovesPtr: number,
  ): void;
  _pick_unplayable_domino_probability_from_moves(
    gamePtr: number,
    playingMovesArrPtr: number,
    numberOfPlayingMovesPtr: number,
  ): void;
  _pass_probability_from_num_moves(
    gamePtr: number,
    numberOfPlayingMoves: number,
  ): number;
}

declare module "@/public/wasm/domino-c" {
  // Emscripten createModule signature; accept any config
  function createModule(config?: Partial<EmscriptenModule>): Promise<DominoAiModule>;
  export default createModule;
}